In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.replace({True:1,False:0})
dataset

C:\Users\PRIYANKA MANI\AppData\Local\Temp\ipykernel_29612\3350150185.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0})


age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [4]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
                    'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
                    'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
                    'appet_yes', 'pe_yes', 'ane_yes']]
independent

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0            0   
1    137.528754  4.627244  10.700000  ...           1          1            0   
2    138.000000  4.400000  12.000000  ...           1          1            0   
3    138.000000  3.200000   8.100000  ...           1          1            0   
4    137.528754  4.627244  11.800000  ...           1          1            0   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...           1          1            0   
395  137.528754  4.627244   8.700000  ...           1          1            0   
396  134.000000  2.700000   9.100000  ...           1          1            0   
397  142.000000  5.500000   8.500000  ...           1          1            0   
398  140.000000  5.000000  16.300000  ...           1          1            0   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0             0        0       0        0          1       1        0  
1             0        0       0        0          1       0        0  
2             0        0       0        0          1       0        0  
3             0        0       0        0          1       0        1  
4             0        0       0        0          1       0        0  
..          ...      ...     ...      ...        ...     ...      ...  
394           0        0       0        0          1       0        0  
395           0        1       1        0          1       0        1  
396           0        1       1        0          0       0        0  
397           0        1       1        0          1       0        1  
398           0        0       0        0          1       0        0  

[399 rows x 27 columns]

In [6]:
dependent=dataset['classification_yes']
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)
X_train, X_test, Y_train, Y_test

(      age     bp   al   su    bgr         bu        sc         sod       pot  \
 240  60.0  100.0  0.0  3.0  263.0  27.000000  1.300000  135.000000  4.300000   
 218  57.0   80.0  0.0  0.0  120.0  48.000000  1.600000  137.528754  4.627244   
 101  42.0   70.0  0.0  0.0   75.0  31.000000  1.200000  141.000000  3.500000   
 311  66.0   70.0  1.0  0.0  248.0  30.000000  1.700000  138.000000  5.300000   
 194  55.0   80.0  0.0  0.0  146.0  57.482105  3.077356  137.528754  4.627244   
 ..    ...    ...  ...  ...    ...        ...       ...         ...       ...   
 323  68.0   70.0  0.0  0.0   98.0  86.000000  4.600000  135.000000  3.400000   
 192  54.0   90.0  1.0  0.0  150.0  18.000000  1.200000  140.000000  4.200000   
 117  45.0   80.0  0.0  0.0  107.0  15.000000  1.000000  141.000000  4.200000   
 47   30.0   80.0  0.0  0.0   89.0  42.000000  0.500000  139.000000  5.000000   
 172  51.0   60.0  0.0  0.0  129.0  25.000000  1.200000  139.000000  5.000000   
 
           hrmo  ...  rbc_

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
#MultinominalNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
              'fit_prior': [True, False]}
grid = GridSearchCV(MultinomialNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)



Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [10]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

[[51  0]
 [ 2 80]]


In [11]:
from sklearn.metrics import roc_auc_score

roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

1.0

In [12]:
#BernoulliNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
              'binarize': [0.0, 0.5, 1.0, None],
              'fit_prior': [True, False]}
grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
                         'binarize': [0.0, 0.5, 1.0, None],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [13]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

[[51  0]
 [ 3 79]]


In [14]:
from sklearn.metrics import roc_auc_score

roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9966523194643712

In [15]:
#ComplementNB
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
              'fit_prior': [True, False],
              'norm': [True, False]}
grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
                         'fit_prior': [True, False], 'norm': [True, False]},
             scoring='f1_weighted', verbose=3)

In [16]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

[[51  0]
 [ 2 80]]


In [17]:
from sklearn.metrics import roc_auc_score

roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

1.0

In [18]:
#GaussianNB
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
param_grid = {'var_smoothing': np.logspace(-11, -7, 10)}
grid = GridSearchCV(GaussianNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e-11, 2.78255940e-11, 7.74263683e-11, 2.15443469e-10,
       5.99484250e-10, 1.66810054e-09, 4.64158883e-09, 1.29154967e-08,
       3.59381366e-08, 1.00000000e-07])},
             scoring='f1_weighted', verbose=3)

In [19]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

[[51  0]
 [ 3 79]]


In [20]:
from sklearn.metrics import roc_auc_score

roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

1.0