In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.replace({True:1,False:0})
dataset

C:\Users\PRIYANKA MANI\AppData\Local\Temp\ipykernel_39508\3350150185.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0})


User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset=dataset.drop("User ID",axis=1)
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [5]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]
independent

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [7]:
dependent=dataset['Purchased']
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)
X_train, X_test, Y_train, Y_test

(     Age  EstimatedSalary  Gender_Male
 218   46            96000            0
 101   28            59000            1
 311   39            96000            1
 194   28            89000            1
 326   41            72000            1
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0
 
 [266 rows x 3 columns],
      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 168   29           148000            1
 150   26            15000            0
 393   60            42000            1
 66    24            19000            1
 240   42           149000            1
 
 [134 rows 

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
#MultinominalNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
              'fit_prior': [True, False]}
grid = GridSearchCV(MultinomialNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)



Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [20]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.62      0.47      0.54        85
           1       0.36      0.51      0.42        49

    accuracy                           0.49       134
   macro avg       0.49      0.49      0.48       134
weighted avg       0.53      0.49      0.49       134

[[40 45]
 [24 25]]


In [22]:
#BernoulliNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
              'binarize': [0.0, 0.5, 1.0, None],
              'fit_prior': [True, False]}
grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
                         'binarize': [0.0, 0.5, 1.0, None],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [23]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.86      0.81      0.84        85
           1       0.70      0.78      0.74        49

    accuracy                           0.80       134
   macro avg       0.78      0.79      0.79       134
weighted avg       0.80      0.80      0.80       134

[[69 16]
 [11 38]]


In [24]:
#CategoricalNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],              
              'fit_prior': [True, False]}
grid = GridSearchCV(CategoricalNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\naive_bayes.py:1504: RuntimeWarning: divide by zero encountered in log
  np.log(smoothed_cat_count) - np.log(smoothed_class_count.reshape(-1, 1))


GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [25]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.66      1.00      0.79        85
           1       1.00      0.10      0.19        49

    accuracy                           0.67       134
   macro avg       0.83      0.55      0.49       134
weighted avg       0.78      0.67      0.57       134

[[85  0]
 [44  5]]


In [26]:
#ComplementNB
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
              'fit_prior': [True, False],
              'norm': [True, False]}
grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [0.0, 0.1, 0.5, 1.0, 10.0],
                         'fit_prior': [True, False], 'norm': [True, False]},
             scoring='f1_weighted', verbose=3)

In [27]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.62      0.47      0.54        85
           1       0.36      0.51      0.42        49

    accuracy                           0.49       134
   macro avg       0.49      0.49      0.48       134
weighted avg       0.53      0.49      0.49       134

[[40 45]
 [24 25]]


In [28]:
#GaussianNB
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
param_grid = {'var_smoothing': np.logspace(-11, -7, 10)}
grid = GridSearchCV(GaussianNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e-11, 2.78255940e-11, 7.74263683e-11, 2.15443469e-10,
       5.99484250e-10, 1.66810054e-09, 4.64158883e-09, 1.29154967e-08,
       3.59381366e-08, 1.00000000e-07])},
             scoring='f1_weighted', verbose=3)

In [29]:
y_pred = grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.91      0.95      0.93        85
           1       0.91      0.84      0.87        49

    accuracy                           0.91       134
   macro avg       0.91      0.89      0.90       134
weighted avg       0.91      0.91      0.91       134

[[81  4]
 [ 8 41]]
